### PR TITLE
windscribe - Phase in streams file

### PR DESCRIPTION
**Pull request by brogers5**
AU is successfully finding and packaging a Windscribe package for each stream I implemented with #21. However, it seems to only be attempting to push the latest package built (currently the Alpha package):

<https://gist.github.com/joachimschmidt557/8a2f24b529db5159a7c189c3b4ccd9a4/684098f3bfb0a3bf2ccad9ae7f158fa659338fc8#windscribe>
<https://gist.github.com/joachimschmidt557/8a2f24b529db5159a7c189c3b4ccd9a4/470ff37dc5a9e6ef72756eb0bc2ef56c7e2012c4#windscribe>

AU is also not adding the locally generated streams file to the Git commit it generates, so it has no way of knowing it previously attempted to build an Alpha package from a clean CI environment. Assuming you'd like to let AU handle building and pushing packages, we'll need to prevent it from continually building an Alpha package.

This PR adds a partially initialized streams file containing [the recently pushed Alpha package](https://community.chocolatey.org/packages/windscribe/2.5.10-alpha)'s version, and uses a dummy value for Beta and Stable to ensure these get built.

A follow-up commit will likely be required later to reset the Stable version after the next run.

### CODE REVIEW

**Comment by brogers5** [comment]
[The last run](https://gist.github.com/joachimschmidt557/8a2f24b529db5159a7c189c3b4ccd9a4/3fddbf22403902943c5290f7ae140dac7fa743b4#windscribe) pushed the beta version. Added a commit for the beta version accordingly.

Once merged, the next run should get everything synced up.

**Comment by brogers5** [comment]
For some reason, [today's AU run](https://gist.github.com/joachimschmidt557/8a2f24b529db5159a7c189c3b4ccd9a4/d90aba023796e71e3802b8d8c4f59f14e6d37d57#windscribe) returned 2.5.14 as the latest stable version. I can't reproduce this result locally. Regardless, updated accordingly.

**Comment by brogers5** [comment]
[All caught up now](https://gist.github.com/joachimschmidt557/8a2f24b529db5159a7c189c3b4ccd9a4/ee4ac21dba560f775c53ae4352dae620ee2c7937#windscribe).

FYI, the new stable versions will require a Package Verifier exemption due to the new OS dependency.

**Comment by joachimschmidt557** [comment]
Thanks a lot!

I will ask the reviewers for an exemption.

**Pull request merged**
