### PR TITLE
Update yt-dlg

### PR DESCRIPTION
**Pull request by Smart123s**
As https://github.com/MrS0m30n3/youtube-dl-gui is now abandoned (it had it's last commit in 2018), I've replaced it with it's continuation, https://github.com/oleksis/youtube-dl-gui.

The main benefit of the new repo (among many others) is that it can actually download videos from YouTube.

I have also updated the `update.ps1` scripts to use the new repo.

### CODE REVIEW

**Comment by joachimschmidt557** [comment]
Hi, thanks for your Pull Request! I currently already have a `yt-dlg.portable` package in this repository: https://github.com/joachimschmidt557/chocolatey-packages-manual-automatic/tree/master/automatic/yt-dlg.portable

I was made aware of `yt-dlg` in https://github.com/chocolatey-community/chocolatey-package-requests/issues/1162 

My first impression was to create a new package with a new name. This updated package has the name `yt-dlg` instead of `youtube-dl-gui`. One of the official repos (and the corresponding GitHub organization) is `yt-dlg`, which I assume is intentional to distinguish it from `youtube-dl-gui` I think.

Would you be ok with me continuing with the new `yt-dlg.portable` and `yt-dlg.install` packages instead of updating the `youtube-dl-gui.portable` and `youtube-dl-gui.install`?

**Comment by Smart123s** [comment]
I'd be totally ok with that. I didn't even realize that you had yt-dlg as well. I'll install that.

**Comment by joachimschmidt557** [comment]
Yeah, I currently have `yt-dlg.portable`: https://community.chocolatey.org/packages/yt-dlg.portable/1.8.2 and I'll add `yt-dlg.install` in a few hours. However, the number of VirusTotal detections on the executable is pretty high (which is common for PyInstaller binaries (e.g. https://community.chocolatey.org/packages/open-stage-control/1.14.3), so I'll probably have to add a notice to these packages as well before they are approved.

**Comment by Smart123s** [comment]
Ok, I'm looking forward to it.

**Comment by opusforlife2** [comment]
Hey @joachimschmidt557. Just a ping to let you know the package is waiting for your action.

**Comment by joachimschmidt557** [comment]
@opusforlife2 Thanks for the reminder, I fixed the issue with `yt-dlg.portable`.

**Pull request closed without merging**
